### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/CO_Prometheus.Stratis#8]
- [x] respawn ermöglichen
- [ ] civilian zeus slots dont work (when used twice?)
- [x] SMA rausschmeißen
- [x] ace hearing raus
- [x] tanoa blufor camo

**Comment by Salbei2500** [comment]
SMA rausgeschmießen, Respawn Parameter hinzugefügt, Tanoa spawn und einen Fehler in der Description.ext gefixt

**Comment by AdlerSalbei** [comment]
Noch ein Bug der exsistiert ist der Spawn auf Tanoa
